#!/usr/bin/env bash

# enable color support of ls and also add handy aliases
if [[ $OS == 'LINUX' ]]; then
    alias ls='ls -Fh --color=auto'
    alias ll='ls -Fhl --color=auto'
    alias la='ls -Fha --color=auto'
    alias lr='ls -fhlrt --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'

elif [[ $OS == 'OSX' ]]; then
    alias ls='ls -FhG'
    alias ll='ls -FhlG'
    alias la='ls -FhaG'
    alias lr='ls -fhlrtG'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Tmux alias
#alias tmux='tmux -2'
alias ta='tmux attach -t'
alias tnew='tmux new -s'
alias tls='tmux ls'
alias tkill='tmux kill-session -t'

# Convenience alias for editing configs
alias ev='vim ~/.vimrc'
alias et='vim ~/.tmux.conf'
alias ez='vim ~/.zshrc'
alias vim='vim -p'
alias nvim='nvim -p'
alias vimno='vim -u NONE'
alias nvimno='nvim -u NONE'


alias jvim='vim -p ~/.vimrc ~/.vim/bundle/jvim/plugin/jvim.vim'
alias jnvim='nvim -p ~/.vimrc ~/.vim/bundle/jvim/plugin/jvim.vim'

#Colorize GCC output
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

printf "${RESET}${GREEN}Shell Aliases$RESET|"

# Convenience alias for mounted volumes (Linux GNOME/KDE)
if [[ -d "/run/user/$UID/gvfs" ]]; then
    alias cdmount='cd "/run/user/$UID/gvfs"'
elif [[ -d "$XDG_RUNTIME_DIR/gvfs" ]]; then
    alias cdmount='cd "$XDG_RUNTIME_DIR/gvfs"'
elif [[ -d "/media/$USER" ]]; then
    alias cdmount='cd "/media/$USER"'
fi
