#!/bin/bash

case "$OSTYPE" in
    solaris*) export OS="SOLARIS" ;;
    darwin*)  export OS="OSX" ;;
    linux*)   export OS="LINUX" ;;
    bsd*)     export OS="BSD" ;;
    msys*)    export OS="WINDOWS" ;;
    *)        export OS="unknown: $OSTYPE" ;;
esac

if [[ "$OS" != 'LINUX' ]]; then
    echo " == OS Detect: $OS == "
else

    # IDs help ---> https://github.com/zyga/os-release-zoo
    source /etc/os-release    #Load OS VARS
    if [[ "$OS" == 'LINUX' ]]; then
        DISTRO="$ID"
        export OS
        export DISTRO
        echo " == OS Detect: $OS/$DISTRO == "
        return 0
    fi
fi

return 0
