#!/bin/bash

# parallel_commands
# https://stackoverflow.com/questions/10909685/run-parallel-multiple-commands-at-once-in-the-same-terminal

# Examples:
# parallel_commands "cmd arg0 arg1 arg2" "other_cmd arg0 arg2 arg3"
# parallel_commands "sleep 1" "sleep 2" "sleep 3" "sleep 4"

for cmd in "$@"; do {
  echo "Process \"$cmd\" started"
  $cmd & pid=$!
  PID_LIST+=" $pid";
} done

trap "kill $PID_LIST" SIGINT

echo "Parallel processes have started"

wait $PID_LIST

echo
echo "All processes have completed"
